import Preloader from "@/components/Preloader";
import "@css/reset.css";
import "@css/searchbar.css";
import "@plugins/animate.min.css";
import "@plugins/bootstrap.min.css";
import "@plugins/icofont.css";
import "@plugins/maginific-popup.min.css";
import "@plugins/nice-select.min.css";
import "@plugins/odometer.css";
import "@plugins/swiper-bundle.min.css";
import "@plugins/uicons.css";
import "./globals.css";

export const metadata = {
  title: "Silver Peacock & Co - Sydney CBD based Accountants & Tax Advisors",
  description:
    "Generated by Silver Peacock & Co - Sydney CBD based Accountants & Tax Advisors",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Preloader />
        {children}
      </body>
    </html>
  );
}
